name: psi4me
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - psi4
  - rdkit
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - scipy
  - scikit-learn
